# Change these first
owner: nimbus9inc # Your GitHub organization or username, where this repository lives
repo: api-monitor # The name of this repository

sites:

  # Static sites
  - name: Nimbus9 Marketing Site
    url: https://nimbusnine.co
    icon: https://nimbus9.co/wp-content/uploads/2016/09/Widget2-150x150.png
    
  - name: Nimbus9 API Documentation
    url: https://api.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Unifi Enterprise
    url: https://unifi-enterprise.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Environment Quality Management
    url: https://eqm.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Site Admin Panel
    url: https://admin.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Partner Quoting Tool
    url: https://quote.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  # SSO
  - name: Nimbus9 SSO
    url: https://sso.nimbus9.io
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  # API Services
  - name: Nimbus9 Auth API
    url: https://api.nimbus9.io/v2/auth/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Automated Demand Response API
    url: https://api.nimbus9.io/v2/adr/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Audit API
    url: https://api.nimbus9.io/v2/audit/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Billing API
    url: https://api.nimbus9.io/v2/billing/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Device Commissioning API
    url: https://api.nimbus9.io/v2/commission/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Device Control API
    url: https://api.nimbus9.io/v2/control/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Event->Condition->Action API
    url: https://api.nimbus9.io/v2/eca/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Floor Plan API
    url: https://api.nimbus9.io/v2/floor-plan/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 HVAC API
    url: https://api.nimbus9.io/v2/hvac/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Metrics API
    url: https://api.nimbus9.io/v2/metrics/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Notification API
    url: https://api.nimbus9.io/v2/notification/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Passport API
    url: https://api.nimbus9.io/v2/passport/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Quote API
    url: https://api.nimbus9.io/v2/quote/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Real-time Update API
    url: https://api.nimbus9.io/v2/update/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Reporting API
    url: https://api.nimbus9.io/v2/report/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Routine Schedule API
    url: https://api.nimbus9.io/v2/astro/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Smart Control API
    url: https://api.nimbus9.io/v2/smart-control/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

  - name: Nimbus9 Switch/Sensor API
    url: https://api.nimbus9.io/v2/switch-sensor/health
    icon: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg

status-website:
  cname: status.nimbus9.io
  logoUrl: https://admin.nimbus9.io/assets/img/nimbus9-logo.svg
  name: Nimbus9, Inc.
  introTitle: "Unifi Platform Service Monitoring"
  introMessage:
  navbar:
    - title: Status
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
